PROJECT_NAME=ERP-STAGGING-NEW

DEPLOY_PATH=D:/Xampp-org/htdocs/erp-stagging-new

BACKUP_PATH=D:/Xampp-org/htdocs/backup

TEMP_DEPLOY_PATH=D:/Xampp-org/htdocs/deployment-temp

PHP_PATH=D:/Xampp-org/php/php.exe

COMPOSER=composer

ENVIRONMENT=STAGING